### ISSUE TITLE
Results folder was not created

### ISSUE THREAD

**Issue by bruno-po** [ufeslabic/parse-facebook#1]
Hello!
I'm trying to get the data for facebook fanpage analysis with this script. I received the follow message:

$ python3.3 parse_facebook.py
Traceback (most recent call last):
  File "parse_facebook.py", line 8, in <module>
    posts()
  File "/home/lahunmen/Documentos/teste_gephi_netvizz_facebook/lib_posts.py", line 68, in posts
    next(csv_in)
StopIteration
Regards!
Bruno

**Comment by ufeslabic** [comment]
If you got this error, the script couldn't read even past the first line of the CSV. When you downloaded the file from Netvizz it was the tab delimited option? Can you post the file on gist or pastebin, or parts of it including the first line?
